### ISSUE TITLE
下载1.14-release版本启动报错

### ISSUE THREAD

**Issue by weishengshui** [yahoo/pulsar#29] opened 2016-09-21 10:07 UTC
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.epoll.IovArray
	at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:62)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:114)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:93)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:80)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:61)
	at org.apache.bookkeeper.client.BookKeeper.getDefaultEventLoopGroup(BookKeeper.java:936)
	at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:243)
	at com.yahoo.pulsar.broker.BookKeeperClientFactoryImpl.create(BookKeeperClientFactoryImpl.java:79)
	at com.yahoo.pulsar.broker.ManagedLedgerClientFactory.<init>(ManagedLedgerClientFactory.java:38)
	at com.yahoo.pulsar.broker.PulsarService.start(PulsarService.java:231)
	at com.yahoo.pulsar.PulsarStandaloneStarter.start(PulsarStandaloneStarter.java:143)
	at com.yahoo.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:175)

**Comment by merlimat** [comment] 2016-09-21 17:39
I cannot reproduce this error. Can you specify the exact steps and the versions for OS / JVM?

**Comment by weishengshui** [comment] 2016-09-22 01:47
JVM
[root@dev3 lib]# java -version
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (build 1.8.0_101-b13)
OpenJDK Server VM (build 25.101-b13, mixed mode)

OS
[root@dev3 lib]# uname -a
Linux dev3 2.6.32-642.1.1.el6.i686 #1 SMP Tue May 31 20:41:01 UTC 2016 i686 i686 i386 GNU/Linux
[root@dev3 lib]# cat /proc/version 
Linux version 2.6.32-642.1.1.el6.i686 (mockbuild@worker1.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Tue May 31 20:41:01 UTC 2016
[root@dev3 lib]#  cat /etc/redhat-release
CentOS release 6.8 (Final)

bug重现步骤：
[root@dev3 ~]#wget  https://github.com/yahoo/pulsar/releases/download/v1.14/pulsar-1.14-bin.tar.gz
[root@dev3 ~]#tar -zvxf  pulsar-1.14-bin.tar.gz
[root@dev3 ~]#cd  pulsar-1.14-bin
[root@dev3 pulsar-1.14-bin]#./bin/pulsar standalone

**Comment by merlimat** [comment] 2016-09-22 06:15
It might be related openjdk vs oraclejdk. In any case in `BookKeeper.getDefaultEventLoopGroup` we should be really catching the `NoClassDefFoundError` and fallback to the NIO event loop.

**Comment by radekg** [comment] 2016-09-24 01:33
Related: https://github.com/netty/netty/issues/4840

**Comment by merlimat** [comment] 2016-09-26 18:36
Committed a fix in bookkeeper branch at https://github.com/yahoo/bookkeeper/commit/89826351a698de7e0fac8d326596d840b8c2aa5e

Will close this issues when updating BK version here

**Closed** 2016-09-27 20:02 UTC
Labels: bug
